package endtoendtests

var validJSONTests = []string{
	"tests/step1/valid.json",
	"tests/step2/valid.json",
	"tests/step2/valid2.json",
	"tests/step2/valid3.json",
	"tests/step2/valid4.json",
	"tests/step2/valid5.json",
	"tests/step2/valid6.json",
	"tests/step2/valid7.json",
	"tests/step2/valid8.json",
	"tests/step2/valid9.json",
	"tests/step2/valid10.json",
	"tests/step2/valid11.json",
	"tests/step2/valid12.json",
	"tests/step2/valid13.json",
	"tests/step2/valid14.json",
	"tests/step2/valid15.json",
	"tests/step2/valid16.json",
	"tests/step2/valid17.json",
	"tests/step3/valid.json",
	"tests/step3/valid2.json",
	"tests/step3/valid3.json",
	"tests/step3/valid4.json",
	"tests/step3/valid5.json",
	"tests/step3/valid6.json",
	"tests/step3/valid7.json",
	"tests/step3/valid8.json",
	"tests/step3/valid9.json",
	"tests/step3/valid10.json",
	"tests/step3/valid11.json",
	"tests/step3/valid12.json",
	"tests/step3/valid13.json",
	"tests/step4/valid.json",
	"tests/step4/valid2.json",
	"tests/step4/valid3.json",
	"tests/step4/valid4.json",
	"tests/step4/valid5.json",
	"tests/step4/valid6.json",
	"tests/step4/valid7.json",
	"tests/step4/valid8.json",
	"tests/step4/valid9.json",
	"tests/step4/valid10.json",
	"tests/step4/valid11.json",
	"tests/step4/valid12.json",
	"tests/huge_json/valid.json",
}

var invalidJSONTests = []struct {
	filePath  string
	errResult string
}{
	{filePath: "tests/step1/invalid.json",
		errResult: "This is an invalid JSON\nMUST be an object, array, number, or string, or false or null or true\n"},
	{filePath: "tests/step2/invalid.json",
		errResult: "This is an invalid JSON\nThere is an object that contains an extra tail comma(s)\n"},
	{filePath: "tests/step2/invalid2.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/invalid3.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/invalid4.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/invalid5.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid6.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/invalid8.json",
		errResult: "This is an invalid JSON\nMultiple values outside of an object or array\n"},
	{filePath: "tests/step2/invalid9.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid10.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid11.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid12.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid13.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid14.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step2/invalid15.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid16.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid17.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid18.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid19.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid20.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid21.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid22.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid23.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid24.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid25.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/invalid26.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid27.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid28.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid29.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid30.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid31.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid32.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid33.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/invalid34.json",
		errResult: "This is an invalid JSON\nThere is an unclosed object\n"},
	{filePath: "tests/step2/invalid35.json",
		errResult: "This is an invalid JSON\nThere is an object that is closed as an array\n"},
	{filePath: "tests/step2/fail2.json",
		errResult: "This is an invalid JSON\nThere is an unclosed array\n"},
	{filePath: "tests/step2/fail3.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/fail4.json",
		errResult: "This is an invalid JSON\nThere is an array that contains an extra tail comma(s)\n"},
	{filePath: "tests/step2/fail5.json",
		errResult: "This is an invalid JSON\nThere is an array that contains an extra tail comma(s)\n"},
	{filePath: "tests/step2/fail6.json",
		errResult: "This is an invalid JSON\nThere is an array that contains an extra advancing comma(s)\n"},
	{filePath: "tests/step2/fail7.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid commas\n"},
	{filePath: "tests/step2/fail8.json",
		errResult: "This is an invalid JSON\nThis is an array that is surrounded by invalid \"][}{\"\n"},
	{filePath: "tests/step2/fail10.json",
		errResult: "This is an invalid JSON\nMultiple values outside of an object or array\n"},
	{filePath: "tests/step2/fail12.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/fail16.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/fail23.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/fail24.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step2/fail33.json",
		errResult: "This is an invalid JSON\nThere is an array that is closed as an object\n"},
	{filePath: "tests/step3/fail9.json",
		errResult: "This is an invalid JSON\nThere is an object that contains an extra tail comma(s)\n"},
	{filePath: "tests/step3/fail13.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/fail14.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, hexadecimal numbers are not allowed\n"},
	{filePath: "tests/step3/fail15.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail17.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail19.json",
		errResult: "This is an invalid JSON\nThere is an object that has a missing (:)\n"},
	{filePath: "tests/step3/fail20.json",
		errResult: "This is an invalid JSON\nThere is an object that has an invalid (:)s\n"},
	{filePath: "tests/step3/fail21.json",
		errResult: "This is an invalid JSON\nThere is an object that has a comma instead of a colon\n"},
	{filePath: "tests/step3/fail22.json",
		errResult: "This is an invalid JSON\nThere is an array that has a (:) instead of a (,)\n"},
	{filePath: "tests/step3/fail25.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail26.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail27.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail28.json",
		errResult: "This is an invalid JSON\nThere is a string that contains tabs or new lines or Illegal backslash escapes\n"},
	{filePath: "tests/step3/fail29.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/fail30.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/fail31.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/fail32.json",
		errResult: "This is an invalid JSON\nThere is an object that is closed with a comma(s)\n"},
	{filePath: "tests/step3/invalid.json",
		errResult: "This is an invalid JSON\nThere is a wrongly written \"false\"\n"},
	{filePath: "tests/step3/invalid2.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid3.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid4.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid5.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid6.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid7.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid8.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid9.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid10.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading +\n"},
	{filePath: "tests/step3/invalid11.json",
		errResult: "This is an invalid JSON\nThere is a wrongly written \"null\"\n"},
	{filePath: "tests/step3/invalid12.json",
		errResult: "This is an invalid JSON\nThere is a wrongly written \"false\"\n"},
	{filePath: "tests/step3/invalid13.json",
		errResult: "This is an invalid JSON\nThere is a wrongly written \"true\"\n"},
	{filePath: "tests/step3/invalid14.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step3/invalid15.json",
		errResult: "This is an invalid JSON\nThere is an object that contains an extra tail comma(s)\n"},
	{filePath: "tests/step3/invalid16.json",
		errResult: "This is an invalid JSON\nThere is an array that contains an extra tail comma(s)\n"},
	{filePath: "tests/step3/invalid17.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step3/invalid18.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step3/invalid19.json",
		errResult: "This is an invalid JSON\n"},
	{filePath: "tests/step3/invalid20.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step3/invalid21.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step3/invalid22.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, hexadecimal numbers are not allowed\n"},
	{filePath: "tests/step3/invalid23.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading +\n"},
	{filePath: "tests/step3/invalid24.json",
		errResult: "This is an invalid JSON\nThere is an array that has an extra comma(s) between some values\n"},
	{filePath: "tests/step3/invalid25.json",
		errResult: "This is an invalid JSON\nThere is an object that has a missing (:)\n"},
	{filePath: "tests/step3/invalid26.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step3/invalid27.json",
		errResult: "This is an invalid JSON\nThere is an array that is closed with a comma(s)\n"},
	{filePath: "tests/step3/invalid28.json",
		errResult: "This is an invalid JSON\nThere is an object that contains an extra advancing comma(s)\n"},
	{filePath: "tests/step3/invalid29.json",
		errResult: "This is an invalid JSON\nThere is a wrongly written \"null\"\n"},
	{filePath: "tests/step3/invalid30.json",
		errResult: "This is an invalid JSON\nThere is an object that has an extra comma(s) between pairs of key:value\n"},
	{filePath: "tests/step4/invalid.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid2.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid3.json",
		errResult: "This is an invalid JSON\nThere is an array that has a missing comma between two values\n"},
	{filePath: "tests/step4/invalid4.json",
		errResult: "This is an invalid JSON\n"},
	{filePath: "tests/step4/invalid5.json",
		errResult: "This is an invalid JSON\nThere is an array that has a missing comma between two values\n"},
	{filePath: "tests/step4/invalid6.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step4/invalid7.json",
		errResult: "This is an invalid JSON\nThere is an invalid number, there is a leading zero\n"},
	{filePath: "tests/step4/invalid8.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid9.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid10.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid11.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
	{filePath: "tests/step4/invalid12.json",
		errResult: "This is an invalid JSON\nThere are ([{)s that are more than (]})s\n"},
	{filePath: "tests/step4/invalid13.json",
		errResult: "This is an invalid JSON\nThere are ([{)s that are fewer than (]})s\n"},
	{filePath: "tests/step4/invalid14.json",
		errResult: "This is an invalid JSON\n"},
	{filePath: "tests/step4/invalid15.json",
		errResult: "This is an invalid JSON\nMultiple values outside of an object or array\n"},
	{filePath: "tests/step4/invalid16.json",
		errResult: "This is an invalid JSON\nThere is an object that has a missing (:)\n"},
	{filePath: "tests/step4/invalid17.json",
		errResult: "This is an invalid JSON\nThere is an object that has an invalid (:)s\n"},
	{filePath: "tests/step4/invalid18.json",
		errResult: "This is an invalid JSON\nThere is an object that has an invalid (:)s\n"},
	{filePath: "tests/step4/invalid19.json",
		errResult: "This is an invalid JSON\nThere are ([{)s that are more than (]})s\n"},
	{filePath: "tests/step4/invalid20.json",
		errResult: "This is an invalid JSON\nThere are ([{)s that are fewer than (]})s\n"},
	{filePath: "tests/huge_json/invalid.json",
		errResult: "This is an invalid JSON\nThere is an object that has a missing (:)\n"},
	{filePath: "tests/huge_json/invalid2.json",
		errResult: "This is an invalid JSON\nThere is a string that is not surrounded correctly by (\"\")\n"},
}
